blueprint:
  name: Sunricher ZGRC-KEY-044 - Short & Long Press Dual Control
  description: |
    Control two separate devices per button using short and long presses on the Sunricher ZGRC-KEY-044 remote.
    Short press toggles one device, long press toggles another.

  domain: automation
  input:
    remote_device:
      name: Remote Device
      description: The Sunricher ZGRC-KEY-044 remote to listen to.
      selector:
        device:
          integration: zha

    # Devices for short press
    button_1_plug:
      name: Short Press - Device for Button 1
      selector:
        entity:
          domain: switch
    button_2_plug:
      name: Short Press - Device for Button 2
      selector:
        entity:
          domain: switch
    button_3_plug:
      name: Short Press - Device for Button 3
      selector:
        entity:
          domain: switch
    button_4_plug:
      name: Short Press - Device for Button 4
      selector:
        entity:
          domain: switch

    # Devices for long press
    button_1_long:
      name: Long Press - Device for Button 1
      selector:
        entity:
          domain: switch
    button_2_long:
      name: Long Press - Device for Button 2
      selector:
        entity:
          domain: switch
    button_3_long:
      name: Long Press - Device for Button 3
      selector:
        entity:
          domain: switch
    button_4_long:
      name: Long Press - Device for Button 4
      selector:
        entity:
          domain: switch

trigger:
  - platform: event
    event_type: zha_event

action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      scene_id: "{{ trigger.event.data.params.scene_id }}"
  - choose:
      # Button 1 - Short Press
      - conditions:
          - "{{ command == 'recall' and scene_id == 1 }}"
        sequence:
          - service: switch.toggle
            target:
              entity_id: !input button_1_plug
      # Button 1 - Long Press
      - conditions:
          - "{{ command == 'store' and scene_id == 1 }}"
        sequence:
          - service: switch.toggle
            target:
              entity_id: !input button_1_long

      # Button 2 - Short Press
      - conditions:
          - "{{ command == 'recall' and scene_id == 2 }}"
        sequence:
          - service: switch.toggle
            target:
              entity_id: !input button_2_plug
      # Button 2 - Long Press
      - conditions:
          - "{{ command == 'store' and scene_id == 2 }}"
        sequence:
          - service: switch.toggle
            target:
              entity_id: !input button_2_long

      # Button 3 - Short Press
      - conditions:
          - "{{ command == 'recall' and scene_id == 3 }}"
        sequence:
          - service: switch.toggle
            target:
              entity_id: !input button_3_plug
      # Button 3 - Long Press
      - conditions:
          - "{{ command == 'store' and scene_id == 3 }}"
        sequence:
          - service: switch.toggle
            target:
              entity_id: !input button_3_long

      # Button 4 - Short Press
      - conditions:
          - "{{ command == 'recall' and scene_id == 4 }}"
        sequence:
          - service: switch.toggle
            target:
              entity_id: !input button_4_plug
      # Button 4 - Long Press
      - conditions:
          - "{{ command == 'store' and scene_id == 4 }}"
        sequence:
          - service: switch.toggle
            target:
              entity_id: !input button_4_long

mode: restart
